language: php

php:
  - '5.6'

env:
  - REVIEWDOG_VERSION=v0.9.12

install:
  - composer update
  - mkdir -p ~/bin/ && export export PATH="~/bin/:$PATH"
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh |
     sh -s -- -b $(go env GOPATH)/bin $REVIEWDOG_VERSION

script:
  - vendor/bin/phpcs --standard=ruleset.xml --report-checkstyle src/** |
      reviewdog -f=checkstyle -name="codesniffer" -reporter=github-pr-check
