language: php

php:
  - '5.6'

install:
  - composer update

jobs:
  include:
    - stage: cs and test
      script:
      - vendor/bin/phpcs --standard=PSR2 src/**
    - stage: cs and test
      - vendor/bin/phpunit
      - php -f coverage-checker.php logs/clover.xml 100
